const { textFactory } = require('../../core/factories');

module.exports = [
  textFactory("caps", "caps", ["upper", "uppercase"]),
  textFactory("lower", "lower", ["lowercase"]),
  textFactory("title", "title", ["titlecase"]),
  textFactory("swapcase", "swapcase", ["swap"]),
  textFactory("reverse", "reverse"),
  textFactory("reversewords", "reversewords"),
  textFactory("sortwords", "sortwords"),
  textFactory("uniquewords", "uniquewords"),
  textFactory("shufflewords", "shufflewords"),
  textFactory("trim", "trim"),
  textFactory("compact", "compact"),
  textFactory("slug", "slug"),
  textFactory("underscore", "underscore"),
  textFactory("dash", "dash"),
  textFactory("dot", "dot"),
  textFactory("spaced", "spaced"),
  textFactory("newline", "newline"),
  textFactory("strikethrough", "strike", ["strike"]),
  textFactory("underline", "underline"),
  textFactory("bold", "bold"),
  textFactory("italic", "italic"),
  textFactory("spoiler", "spoiler"),
  textFactory("codeblock", "code", ["monospace"]),
  textFactory("quoteformat", "quote"),
  textFactory("leet", "leet"),
  textFactory("altcaps", "mock", ["mock"]),
  textFactory("vaporwave", "vaporwave", ["wide"]),
  textFactory("bubble", "bubble", ["circletext"]),
  textFactory("upsidedown", "upsidedown", ["fliptext"]),
  textFactory("vowels", "vowels"),
  textFactory("novowels", "novowels"),
  textFactory("digits", "digits"),
  textFactory("nodigits", "nodigits"),
  textFactory("letters", "letters"),
  textFactory("nospaces", "nospaces"),
  textFactory("nosymbols", "nosymbols"),
  textFactory("firstword", "firstword"),
  textFactory("lastword", "lastword"),
  textFactory("firstchar", "firstchar"),
  textFactory("lastchar", "lastchar"),
  textFactory("wrap40", "wrap40"),
  textFactory("wrap60", "wrap60"),
  textFactory("wrap80", "wrap80"),
  textFactory("rot13", "rot13"),
  textFactory("morse", "morse"),
  textFactory("demorse", "demorse"),
  textFactory("base64text", "base64"),
  textFactory("hextext", "hex"),
  textFactory("unicode", "unicode"),
  textFactory("charcodes", "charcodes"),
  textFactory("palindrome", "palindrome"),
  textFactory("brackets", "brackets"),
  textFactory("parentheses", "parentheses"),
  textFactory("quotes", "quotes"),
  textFactory("backticks", "backticks"),
  textFactory("slashify", "slash"),
  textFactory("pipeify", "pipe"),
  textFactory("commafy", "comma"),
  textFactory("countchars", "countchars", ["charlen"]),
  textFactory("countwords", "countwords", ["wordlen"]),
  textFactory("countlines", "countlines", ["linelen"]),
  textFactory("countvowels", "countvowels"),
  textFactory("countdigits", "countdigits"),
  textFactory("countspaces", "countspaces"),
  textFactory("countupper", "countupper"),
  textFactory("countlower", "countlower"),
  textFactory("numbersum", "numbersum"),
  textFactory("nodupchars", "nodupchars"),
  textFactory("repeatword", "repeat", ["repeat"]),
  textFactory("censor", "censor")
];